server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: liaorui
    password: 6109119089
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size:  50MB
      max-request-size: 10MB
mybatis:
  mapper-locations: mapper/*.xml
logging:
  level:
    com.mall.app.dao: debug
